### ISSUE TITLE
Skip base64, send colors only

### ISSUE THREAD

**Issue by fregante** [krasimir/coloor#1]
I'm not sure if I understood the whole mechanism but if you're using canvas you might as well skip the base64 and just send over the 9 colors that will make up the image.

**Comment by krasimir** [comment]
Well, even though this is possible I was thinking that it is a good idea to not simply provide dominant colors but literally scale down the image to 9x9 so we get a better representation of the image's colors

**Comment by fregante** [comment]
I don't mean the dominant colors. You're scaling down the image and sending that as base64. What I suggest is scaling it down, read the 9 pixels and send that instead. They're much lighter

**Comment by krasimir** [comment]
If it is possible to read the colors in the exact order then maybe it will be shorter indeed. But later in the client-side I'll have to create base64 image from these colors again.

**Comment by fregante** [comment]
Aren't you using canvas to re-create the placeholder image with the correct size starting from the 3x3 base64 and setting an updated base64 (e.g. 300x100)?

**Comment by krasimir** [comment]
Yep, that's what I meant. I'm anyway using canvas on the client-side so if we skip the slightly bigger markup size the result is almost the same. 

_By the way I started the repo working with colors only. They could lead to some interesting UI experiences._

**Comment by tomByrer** [comment]
I think @bfred-it is thinking what I was thinking; why directly interact with canvas at all?  Why not just send a `thumbnail-9x9.gif` & blur?

**Comment by krasimir** [comment]
That's because of the layout shifts. Very often the images are not square sizes. What if we have 600x300 photo. We need a thumbnail which is 8x4 for example. Another which which Coloor is doing is resizing the preview to the original size. So:

```
--------- in node ---------
original image (600x300 jpg)
  |
build step
  |
preview image (8x4 base64)
  |
--------- network ---------
  |
browser loads markup that contains 8x4 base64 string
  |
dynamically with canvas resizes 8x4 to 600x300
  |
user sees 600x300 base64 preview
  |
we preload the original image
  |
we swap the preview with the original one
```

What I wanted is to provide a preview with the same size as the original image. That's because I don't want to force the developer setting `width` or `height` of the `<img>` tag. Without that the utility will indeed show 8x4 image but the developer should take care for match the size of the original file.

**Comment by fregante** [comment]
Yes! So, my point was this (marked with ###)

```
--------- in node ---------
original image (600x300 jpg)
  |
build step
  |
preview image (8x4 base64) ### SKIP THIS STEP
  |
--------- network ---------
  |
browser loads markup that contains 8x4 base64 string ### SKIP rendering base64 image that isn't going to appear anyway
  |
dynamically with canvas resizes 8x4 to 600x300
  |
user sees 600x300 base64 preview
  |
we preload the original image
  |
we swap the preview with the original one
```

So I suggest this:

```
--------- in node ---------
original image (600x300 jpg)
  |
build step
  |
send array of 8x4 pixels ### much lighter byte-wise and CPU-wise
  |
--------- network ---------
  |
browser loads markup that contains array of pixels ### lighter page
  |
dynamically with canvas draws the array of pixels on 600x300 ###
  |
user sees 600x300 base64 preview
  |
we preload the original image
  |
we swap the preview with the original one
```

**Comment by krasimir** [comment]
I'll try following your approach next weekend. It will be a little bit tricky though because we have to reconstruct the preview (keep the position of the pixels). Another idea which I had with my implementation is to allow custom size previews. I mean not only 9x9 or 8x<something> but bigger variants like 12x<something> for example.

**Comment by fregante** [comment]
The information sent over could be formatted as:
`3,2,AABBCC,BBCCAA,EEFFCC,003355,224477,AABB44`

And then:

``` js
opts = opts.split(',');
var width = opts.shift()
var height = opts.shift()
var pixels = opts;
```

Is the semi-equivalent of the base64 uri: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAYAAAAEAQMAAACXytwAAAAAA1BMVEUAAACnej3aAAAAFElEQVR4Xi3AIQEAAACAIP+vtkAMAAgAAYAbWg4AAAAASUVORK5CYII=`

**Comment by krasimir** [comment]
Yep. I think the tricky part will be the fetching of the colors. Will keep you guys posted about this approach.

**Comment by tomByrer** [comment]
> Another idea which I had with my implementation is to allow custom size previews. I mean not only 9x9 or 8x but bigger variants like 12x for example.

I am hoping for this; thanks!  A full-page hero could use more 'pixels' than a small thumbnail.  Maybe

``` js
blockLengthMin = 100;
blockLengthX = Math.round( img.x / blockLengthMin );
blockLengthY = Math.round( img.y / blockLengthMin );
```

I'm still wondering if this is better:

```
--------- in node ---------
original image (600x300 jpg)
  v
calculate size
  v
resize image
  v
encode to BASE64
  |
preview image (6x3 base64)
  |
--------- network ---------
  |
browser loads markup that contains 6x3 base64 GIF
  v
Browser automatically rescales & blurs thanks to
<... style="filter:blur(9px);-webkit-filter:blur(9px);" width=600 height=300>
  |
user sees 600x300 base64 preview
  |
we preload the original image
  |
we swap the preview with the original one
```

I'm thinking there might be GPU acceleration for image resizing, or perhaps just more optimized than JS `.drawImage()`.
